### ISSUE TITLE
Possible Security Problems

### ISSUE THREAD

**Issue by ctindall** [mozilla/mozdef-event-framework-template#15]
Hey there! I noticed some possible problems in some code in this repo. A quick summary of a few of them is below, but let me know if you're interested in seeing a full report or talking about cloud security in general.

---

**severity:** serious

**filename:** `./templates/codepipeline-cf-template.yml`

**line number(s):** [181, 352, 430]

**resource(s):** 

IAM policy should not allow * action

---

**severity:** warning

**filename:** `./templates/codepipeline-cf-template.yml`

**line number(s):** [537]

**resource(s):** 

CodeBuild project should specify an EncryptionKey value

---

**severity:** warning

**filename:** `./templates/codepipeline-cf-template.yml`

**line number(s):** [181, 352, 430]

**resource(s):** 

IAM policy should not allow * resource

---

**severity:** warning

**filename:** `./templates/codepipeline-cf-template.yml`

**line number(s):** [110, 166, 337, 415]

**resource(s):** 

Resource found with an explicit name, this disallows updates that require replacement of this resource

**Comment by Phrozyn** [comment]
Hello! We thank you for the review.
This repo is currently a work in progress, we are aware of the "*" resources and such, which we will be cleaning up once we are done with the workflow documentation and testing in dev.
We very much appreciate the concern!

**Comment by Phrozyn** [comment]
Closing this as we've addressed the issues as needed.
